defaults/main.yml, templates/perun-web-gui.properties.j2
- New property registrar.findSimilarUsers.disabled was added to the
perun-web-gui template. Default value (false) was set to the default main file.
=> Added new property to old gui templates

templates/perun.properties.j2
- dbType property is no longer used in perun
=> Deleted db.type

defaults/main.yml, tasks/perun_ldapc.yml, tasks/perun_rpc.yml, templates/perun-apps-config.yml.j2
- this template represents a perun-apps-config.yml file which will be
created in /etc/perun/rpc/ and /etc/perun/ldapc/.
Its default content is composed from the main rpc hostname, ngui
hostname and rpc aliases. It can be overriden in any vars file by variable
perun_apps_config.
=> New template for perun-apps-config.yml

templates/shibboleth2.xml.j2
- consistentAddress set to "false" so the session does not depend on IP address.
=> Shibboleth sessions set consistentAddress

defaults/main.yml, templates/instanceConfig.json.j2
- Admin gui footer is now configurable, therefore the template and
default set up changed. The template takes whole variable
perun_ngui_footer and converts it to json. This variable is by default
empty so the defaultConfig footer is be used.
=> Admin gui footer config

defaults/main.yml, templates/perun.properties.j2
- We needed to have an option to disable account linking also on
backend. Therefore, new property was added. The GUI property has the rpc
value set by default.
=> New rpc property findSimilarUsersDisabled

templates/perun-apps-config.yml.j2
- Internal logic required entries for apps locations to be
present and set to empty string even if app is not used.
=> Create empty entries for disabled apps in perun-apps-config.yml

templates/instance_configs/consolidatorInstanceConfig.json.j2, templates/instance_configs/instanceConfig.json.j2, templates/instance_configs/linkerInstanceConfig.json.j2, templates/instance_configs/profileInstanceConfig.json.j2, templates/sites-enabled/perun-admin.conf.j2, templates/sites-enabled/perun-consolidator.conf.j2, templates/sites-enabled/perun-linker.conf.j2, templates/sites-enabled/perun-profile.conf.j2
- In cases of migration of proxy endpoints we must be able to set
custom API URL for each application (different from perun_api_hostname,
or perun_rpc_hostname).
- Also overide CSP settings in Apache config for each app.
=> Allow setting custom api_url in instanceConfig.json

defaults/main.yml, templates/perun-cli-env.j2, templates/perun-engine.j2
- Because we use various API domains for Perun we must be able to point CLI and Engine to the right one.
- By default we use "perun_api_hostname", which is by default "perun_rpc_hostname" but each instance can override this value with own config.
=> Use proper API domains for CLI and Engine

templates/perun-apps-config.yml.j2, templates/perun-web-gui.properties.j2
- Removed "perun_oldgui_newAdminGuiAlert" property from perun-web-gui.properties file.
- It was replaced with "perun_oldgui_alert" in perun-apps-config.yml.
=> Removed perun_oldgui_newAdminGuiAlert property

defaults/main.yml, templates/instance_configs/instanceConfig.json.j2
- Allow to set auto_oath_redirect and auto_service_access_redirect for the admin GUI defaulting to same values as in defaultConfig.json.
- It will be used in the future for the CESNET and VSUP instances.
=> Allow setting more properties of new Admin GUI

templates/instance_configs/instanceConfig.json.j2
- Property in config actually expect the object with mapping of language to string.
- Not needed for consolidator/linker. Probably needed for pwd reset, but it is not yet supported app in the ansible.
=> Fix document_title property of admin gui config

defaults/main.yml, templates/perun.properties.j2
- Adedd missing _rpc_ into the ansible properties names.
=> Unified naming of ansible properties for perun.properties

defaults/main.yml, tasks/perun_rpc.yml, templates/perun-notification.properties.j2, templates/perun.properties.j2
- It is no longer used in new release v22.0.0, since the only used property was moved to perun.properties.
- Temporarily add task for perun_rpc to remove existing prop file.
=> Removed perun-notification.proprties

defaults/main.yml, templates/perun.properties.j2
* This property switches between two possible scenarios.
* If this property is set to true, then the deletion of users will be enabled and set as well as a default method. During the deletion user's logins will be blocked. The anonymization will be disabled.
* If this property is set to false, then the anonymization of users will enabled and the deletion will be disabled.
=> feat: added new rpc property userDeletionForced

templates/sites-enabled/perun-api.conf.j2
- Manipulate tomcat PERUNSESSION cookie to be SameSite=None when cors origin matches. Also allow browser to send credentials.
- This allows us to keep internal tomcat session, and we do not have to reinitialize it with every request (also saving creation of two audit messages).
- This could technically allow cross site scripting, but we don't have any webapp on the API domain, we limit this modification only to our trusted domains, and we still expect request to contain authorization header, which is constructed inside the app and not transferred by cookies.
=> Allow keeping session for new GUI apps

defaults/main.yml, templates/sites-enabled/perun.conf.j2
- Added variables perun_apache_old_admin_gui_disabled and perun_apache_old_profile_disabled that allows us to "disable" old applications. Meaning that when someone wants to access old profile or admin gui, he will be redirected to the new application. Default is that old application are enabled.
=> Added option to disable old profile and admin gui

templates/shibboleth/attribute-map.xml.j2
- EGI uses officiali voPerson schema OIDs while Geant is using attributes in their own schema. Official attributes are now part of the default config.
=> Add voPerson schema attributes to default attribute-map.xml

tasks/perun_rpc.yml
- We couldn't set swap limit to the container since it was not supported in kernel. It resulted in false "changed" flag for the container creation on each run and container was not restarted beacuse of it.
- Now we don't set swap limit, since enabling it in kernel means 1% memory and 10% performance degradation and we don't actually need it.
=> Do not set swap limit since it's not supported by kernel

defaults/main.yml, templates/sites-enabled/perun.conf.j2
- We do not build WUI Admin app for a long time, so there is no need to have it in apache config (under /wui/ path).
- Removed also from cache headers conditions together with affiliation app, which has been deleted too.
- Removed default value property for "perun_apache_wui_enabled".
=> Removed wui admin part of apache config

templates/sites-enabled/perun.conf.j2
- Modify cookies and headers only for the allowed CORS domains where we have new UI. This make sure we keep session also on instances with alternative api domain (with two different oidc servers).
=> Allow session cookies for new GUI apps also on the main domain

templates/sites-enabled/perun.conf.j2
- Added /img and /static to opened endpoints when in maintenance.
- Added also /external which is used on EGI.
=> Make sure static resources are available during maintenance

defaults/main.yml, templates/perun.properties.j2
* mfa information is now retrieved from the introspection endpoint, rename properties to reflect this
* acr and auth timestamp claim names should follow OpenID standards and hence do not have to be configurable
=> Edit MFA properties names + remove unused properties

defaults/main.yml, templates/shibboleth/shibboleth2.xml.j2
- For instances like CESNET/EGI where multiple domains are used, SAML2 logout doesn't work since proxy won't return us to the expected domain, but rather the primary one. We can't specify multiple endpoints in the metadata, only first found is used in logout redirect. Problem is solved by using only local logout with forcing authn on consolidator endpoints.
- Default is still using SAML2 logout. To force local logout only set "perun_apache_shibboleth_sp_session_initiators" to "yes".
=> Allow forcing only local logout on Perun SP

templates/instance_configs/consolidatorInstanceConfig.json.j2, templates/instance_configs/instanceConfig.json.j2, templates/instance_configs/linkerInstanceConfig.json.j2, templates/instance_configs/profileInstanceConfig.json.j2, templates/sites-enabled/perun-consolidator.conf.j2, templates/sites-enabled/perun-linker.conf.j2
- We can now specify full custom API URL, which will be used in instanceConfig.json and profileInstanceConfig.json. It allows us to switch service-access to a different authz provider (eg. ldap on VSUP).
- Changed "url" to "hostname" in API variables for new consolidator and linker, since it actually changes only the hostname and not full URL.
=> Support custom API url for NGUI admin and profile

defaults/main.yml
- There is no agenda left under the settings page in the default displayed tabs in new profile, hence empty page is displayed. It is confusing to users so settings page is now hidden by default.
=> Removed settings from default profile tabs

tasks/perun_rpc.yml
- /etc/perun/perun-oidc-config.yml file inside the perun_rpc container is used by OIDC version of CLI for autoconfiguration purposes.
- Source file is expected to be in the "files" root for each instance.
=> Include perun-oidc-config.yml in perun_rpc configuration

tasks/perun_rpc.yml
- Task is no longer needed, since it was deployed everywhere with version v22.0.0, and we are now at v28.0.2.
=> Removed task "delete unused perun-notifications.properties"

tasks/perun_rpc.yml
- Create or delete perun-oidc-config.yml file on the managed perun instance based on its existence in perun instance files.
=> Correctly handle perun-oidc-config.yml file

defaults/main.yml, handlers/main.yml, tasks/main.yml, tasks/perun_auditlogger.yml, tasks/perun_certs.yml, tasks/perun_users.yml, tasks/perun_volumes.yml, templates/logback-auditlogger.xml.j2, templates/perun-auditlogger.j2, templates/perun-auditlogger.properties.j2
- Auditlogger app is NOT installed by default.
- Added necessary config files and installation tasks.
- Create perunalg group and user.
- Restart it when certificates changes.
- Mount /home/perunalg and /etc/perun/auditlogger/.
=> Support for Auditlogger application

defaults/main.yml, templates/perun-web-gui.properties.j2
- We want address different from generic perun backup email.
- Default fallback to previous behavior.
=> Allow customization of support email for password reset

defaults/main.yml, tasks/main.yml
- Introduce perun_* variables in config for cesnet.remote_logging.
- Ditch vinovago from variable names.
- Use default config from the role in perun_docker_server.
=> Make remote logging config configurable per instance

defaults/main.yml, templates/perun-registrar-lib.properties.j2, templates/perun.properties.j2
- New properties allow to configure default "replyTo" values for sent notifications from registrar or core (mailchange, pwd change).
=> Support new replyTo properties for core and registrar

tasks/perun_auditlogger.yml, tasks/perun_ldapc.yml
- Override default check of external dependencies on startup for perun_auditlogger and perun_ldapc since they are not actually used/required and are not present.
=> Clear default external deps for auditlogger and ldapc

defaults/main.yml, templates/perun.properties.j2
- Allow changing default value for "perun.group.structure. maxConcurrentGroupsStructuresToSynchronize" in perun.properties.
=> Allow customization of existing property in perun.properties

defaults/main.yml, templates/perun.properties.j2
- Introduce "perun_rpc_additional_dont_lookup_users" variable to allow extension of default list of principals for "perun.dont.lookup.users" property in perun.properties. Previously it was only possible to override this configuration, now values can be just added to the default list using this new config option.
- Removed "perunController" principal from default config since it's no longer used anywhere in the sources.
=> Allow extension of perun_rpc_dont_lookup_users variable

templates/sites-enabled/perun.conf.j2
- If "perun_apache_consolidator_custom_sp" is defined, it replaces
default SP config for perun default site (path to /Shibboleth.sso etc.).
This logic can be used to create additional site (eg. signup-like) with
same template, using different SP config.
- "perun_apache_fed_initiators" can now specify new property
"consolidatorApplicationId" which will be used for consolidator
prefixes (eg. /fed-ic/) as applicationId. This allows us to have
multiple consolidator SPs in one config.
=> Allow setting custom SP config for main perun site

templates/sites-enabled/perun.conf.j2
- We do not have WUI app for publications, so it doesn't have to be a part of regex for Apache no-cache headers.
=> Removed /publications/ from apache headers regex

defaults/main.yml, templates/instance_configs/instanceConfig.json.j2, templates/instance_configs/profileInstanceConfig.json.j2, templates/instance_configs/pwdresetInstanceConfig.json.j2
- Support for admin, profile and pwdreset config.
- By default we have only empty filter "".
- Filters for profile and pwdreset defaults to admin filter.
- Filters are picked and used by GUI based on URL param "idpFilter".
=> Allow setting authz filter for new GUI

tasks/perun_rpc.yml
- Allows us to modify Tomcat opts per instance (similar logic like we do for Apache).
- Content of the file is included in "setenv.sh" script used when starting the Tomcat.
- New version of the perun_rpc image is needed.
=> Deploy also tomcat_init.sh if present in files

templates/sites-enabled/perun-api-cert.conf.j2
- Updated template for cert-only API domain. We must include subject/issuer and other cert variables in AJP request to tomcat, otherwise user is not recognized.
=> Forward cert variables to AJP on api-cert domain

defaults/main.yml, templates/perun.properties.j2
- Reordered MFA/StepUp/UserInfoEndpoint entries.
- Convert enforceMfa and requestUserInfoEndpoint to boolean variables.
- Change default of perun_rpc_introspectionEndpoint_mfaAcrValue variable to "https://refeds.org/profile/mfa"
- Fixed missing newline when printing perun_rpc_app_allowed_roles into perun.properties
=> Fixed perun.properties template

defaults/main.yml, tasks/perun_rpc.yml, templates/perun-cabinet.properties.j2
- This config file is no longer used. It was used only for tests. Make sure it is removed from all deployments.
=> Remove unused perun-cabinet.properties from perun_rpc

tasks/perun_rpc.yml
- File has been removed from all instances already.
=> Remove task for perun-cabinet.properties deletion.

defaults/main.yml, templates/sites-enabled/perun.conf.j2
- Set "perun_apache_csp_default_src" to change the value, by default empty.
=> Allow extending default-src rule of CSP on main perun site

templates/perun-web-gui.properties.j2
Remove space from the join string. Caused properties to be ignored. Properly, values of this setting need to be separated just by comma.
=> fix: 🐛 joining of registrar.hideProxy values

tasks/postgres.yml
- Manual upgrade using playbook_upgrade_postgres_minor.yml holds them correctly, but it was missing in playbook_perun.yml (postgresql.yml tasks).
=> Hold all postgresql packages after clean perun install

defaults/main.yml
- Limit postgres access to CESNET EduVPN and MUNI EduVPN for ICS employees.
- Limit portainer access to same (added CESNET IPv4 VPN rules, limit MUNI scope)
=> Update default FW for postgres and portainer

defaults/main.yml, tasks/os_setup.yml
- Requires cesnet.metacentrum_monitoring role version v4.1.0
- Automatically copy files from perun_instance/check_mk/*.cfg to /etc/check_mk/ for metacentrum monitoring to notice.
=> Copy check_mk config from each instance files by default

tasks/perun_sync.yml
- New version of generic_json_gen slave script expect service config in a different location. Create necessary directory a pre file in /etc/perun/generic_json_distributed_authorization.d/.
=> Update config for distributed authorization

defaults/main.yml, templates/perun-web-gui.properties.j2
- Since perun v44.0.0 VO creation in old GUI is handled by new VOCREATOR role, by default nobody can create VO (except for perun admin).
- Removed config "disableCreateVo" from perun-web-gui.properties.
- Removed config "perun_oldgui_disableCreateVo" from ansible role (default was false).
=> Removed option to disable vo creation button in old GUI

defaults/main.yml, templates/perun.properties.j2
New config options required by perun v44.1.0 can be configured using following vars and have following defaults. They are used to configure handling of personal data on profile (allow changes to name, organization and email and whether it requires approval).
- perun_rpc_personal_enable_linked_name: no
- perun_rpc_personal_enable_custom_name: no
- perun_rpc_personal_custom_name_requires_approve: no
- perun_rpc_personal_enable_linked_organization: no
- perun_rpc_personal_enable_custom_organization: no
- perun_rpc_personal_custom_organization_requires_approve: no
- perun_rpc_personal_enable_linked_email: no
- perun_rpc_personal_enable_custom_email: yes
- perun_rpc_personal_custom_email_requires_approve: yes
=> Added new config options in perun.properties required by v44.1.0

defaults/main.yml, templates/instance_configs/consolidatorInstanceConfig.json.j2, templates/instance_configs/instanceConfig.json.j2, templates/instance_configs/profileInstanceConfig.json.j2, templates/instance_configs/publicationsInstanceConfig.json.j2
- Shortcuts to other "apps" in a header of perun NGUI apps can now contain also links to external websites/apps.
- Supported in admin, profile, publications and consolidator apps by variables named like:
"perun_ngui_[app]_other_apps_custom".
- Expected format for config value is same as standard other_apps, but instead of fixed "keys"
representing apps we can use custom URLs.
=> Support other_apps_custom in NGUI configuration since v18.6.0 (perun v47.0.0)

defaults/main.yml, templates/perun.properties.j2
- New property perun.globalSearchLimit can limit number of results for all entities in global search in GUI.
- Default is 4 results for each entity.
- Value is configurable by ansible var "perun_rpc_global_search_limit".
- Property has been added for perun v47.1.0.
=> Add perun.globalSearchLimit property to perun.properties

defaults/main.yml, templates/instance_configs/instanceConfig.json.j2
- Add "display_search" property to Admin GUI instance config.
- It can be configured by "perun_ngui_display_search" ansible property, default is false.
- Enabling this shows global search input in Admin GUI header. To define who is able to perform the search (and see the input) configure "globalSearch_String_policy" policy for API backend method.
=> Allow enablement of global search in Admin GUI.

defaults/main.yml, tasks/perun_engine.yml
- Formerly we used gen/send scripts provided by perun, then local scripts in sites repository relevant to a specific machine and then local scripts manually managed on machine. This logic is now extended with usage of custom GIT repository.
- You can enable this by setting path to the GIT repository in new variable "perun_engine_services_repo" and specifying version in "perun_engine_services_repo_version".
- Ensure perun_engine container is restarted when services from custom git repository are changed.
- New order of gen/send scripts deployment (overwrite/replacement) is:
- scripts from docker image (perun release)
- scripts from custom git repo defined by variable
- scripts from instance deployment (perun_sites)
- manually managed scripts from local folders on the machine
=> Allow engine to use local git repository for default gen/send scripts

templates/perun-dispatcher.properties.j2
- "perun_dispatcher_task_poll_wait" ansible var can be used to configure timeout for waiting tasks queue (time until we re-check forced tasks).
- "perun_dispatcher_task_reschedule" ansible var can be used to configure timeout after which we run propagation maintainer thread checking for done tasks with midified source data or error/stuck tasks.
Both vars have no default in ansible and are not used until defined in your group/host vars. In Perun default timeout for both is 10000 ms.
=> Added new config options for perun-dispatcher.properties

defaults/main.yml, templates/instance_configs/consolidatorInstanceConfig.json.j2, templates/instance_configs/instanceConfig.json.j2, templates/instance_configs/linkerInstanceConfig.json.j2, templates/instance_configs/profileInstanceConfig.json.j2, templates/instance_configs/publicationsInstanceConfig.json.j2, templates/instance_configs/pwdresetInstanceConfig.json.j2
- Added "oauth_acr_value" config option to instanceConfig.json templates for all NGUI apps.
- Default values in vars are the same as default in NGUI code, password protected transport, sfa, mfa.
- Added "perun_ngui_admin_oauth_acr_value" which can be set to change ACR values for all apps (admin gui). Each app can override this default with properties like "perun_ngui_profile_oauth_acr_value" etc.
=> Make oauth acr values configurable for NGUI apps

defaults/main.yml, templates/perun-web-gui.properties.j2
- "wayf.authnContextClassRef" property has been added to "perun-web-gui.properties" templates.
- It allows to configure default authn context class ref URL param for requests from registrar and consolidator in order to join identities.
- Added "perun_oldgui_wayf_authnContextClassRef" ansible var to configure this property which can be set to empty, but defaults to backward compatible value.
=> Support customization of authnContextClassRef in consolidator

defaults/main.yml, tasks/perun_journald.yml
- We had fixed journald template with limits depending on size of the /var/log/ volume.
- Now we can redefine whole template by setting content to "perun_journald_config" var.
=> Make journald config template configurable

defaults/main.yml, tasks/main.yml
- Set "remote_logging_template" when using cesnet.remote_logging from "perun_remote_logging_template" varaible defaulting to "remote_logging.j2" which is present within the role.
- You can change template file by setting a different filename (path) in the instance vars.
- Requires cesnet.remote_logging version v1.8
=> Support passing custom template file for remote logging
