CESNET/ansible-role-perun-docker-server

defaults/main.yml, templates/perun.properties.j2
- Added new configuration property to specify validation window for account
activation.
=> New config property accountActivation.validationWindow

defaults/main.yml, templates/perun.properties.j2
- Added new configuration properties attributesToAnonymize and attributesToKeep
for user anonymization.
=> User anonymization config properties

templates/perun.properties.j2
- This property in perun.properties was not configurable so I've added
that option.
=> loginnamespace generated configurable

templates/perun-web-gui.properties.j2
* Added new property to the `perun-web-gui.properties` file named
`newAdminGuiAlert`.
=> newAdminGuiAlert property

templates/perun-web-gui.properties.j2
- added new property to perun-web-gui.properties representing list of proxies we want to hide in VO/Group registration
=> Added registrar.hideProxy

tasks/perun_rpc.yml
- Rpc was not restarted therefore changes were not applied. Now it is
fixed.
=> restart rpc after perun-roles reloaded

defaults/main.yml, templates/perun.properties.j2
* This property indicated whether consents are required throughout Perun. Defaul value is false.
=> feat: added new rpc property forceConsents

defaults/main.yml, tasks/perun_apache.yml, tasks/perun_certs.yml, tasks/perun_config.yml, templates/consolidatorInstanceConfig.json.j2, templates/linkerInstanceConfig.json.j2, templates/perun-consolidator.conf.j2, templates/perun-linker.conf.j2, templates/profileInstanceConfig.json.j2
* add apache config
* add instanceConfig
* add new properies to main.yml
=> feat: added full configuration for Linker and Consolidator

templates/linkerInstanceConfig.json.j2
=> fix: fix linker instance config

defaults/main.yml, templates/perun-web-gui.properties.j2
Use variable *perun_oldgui_registrar_hide_proxy* to set EntityIDs of
proxies that should be hidden on the similar user found.
=> feat: 🎸 Added option to set the WUI registrar.hideProxy option

defaults/main.yml
Added link to admin gui to default config of profile
=> Added link to admin gui to default config of profile

templates/instance_configs/profileInstanceConfig.json.j2
* fixed property in user profile instance config
=> fix: fixed property in user profile instance config

defaults/main.yml, templates/perun.properties.j2
* extended properties with MFA
=> feat: extended properties to user info endpoint call

templates/perun-roles.yml.j2
* added new property display_name to docs
=> feat: new pern_role_management property

defaults/main.yml
- Set validation window to 24 hours for password reset and mail change.
=> Changed default values for validation windows

defaults/main.yml, templates/instance_configs/instanceConfig.json.j2
* This property has been already added to rpc, we also need this property in instance config.
=> feat: added property user_deletion_forced to admin instance config

defaults/main.yml, templates/instance_configs/consolidatorInstanceConfig.json.j2, templates/instance_configs/instanceConfig.json.j2, templates/instance_configs/profileInstanceConfig.json.j2
* According to this property is handled local/proxy logout and related post-logout redirect.
=> feat: added property proxy_logout to admin, profile and consolidator instanceConfig

defaults/main.yml, tasks/perun_rpc.yml, templates/perun-namespaces.properties.j2
- It is used by login-namespace attribute modules to determine constrainsts and exceptions for the logins of specific namespace.
=> Added perun-namespaces.properties configuration

templates/perun-web-gui.properties.j2
- It supposed to be list in properties files, not json.
=> Fix formating of perun_rpc_reset_pwd_emails in perun-web-gui.properties

tasks/perun_rpc.yml
- We must make it conditional.
=> Temporarily disable creation of perun-oidc-config.yml

defaults/main.yml
- Also by default inherit version of perun_rpc container
=> Fixed version definition for perun_auditlogger container

tasks/perun_postgres.yml
- Changed GitHub source to GitLab.
=> Download perun DB SQL file from GitLab

defaults/main.yml, templates/perun.properties.j2
- Added property "perun.externalProgramsDependencies" to perun.properties file with default values. It is used to check that external dependencies are installed.
=> Added new property to perun.properties

defaults/main.yml, tasks/perun_apache.yml, templates/instance_configs/publicationsInstanceConfig.json.j2, templates/sites-enabled/perun-publications.conf.j2
- By default it is disabled.
- Copy apache site and instance config.
- Added default config.
NOTE: Some generic instance config properties
are probably not supported by the app itself.
=> Added support for new Publications GUI

defaults/main.yml, templates/perun-dispatcher.properties.j2
- Include ansible comment in perun-dispatcher.properties template
=> Allow enabling/disabling dispatcher

templates/maintenance/401.json, templates/maintenance/403.json, templates/maintenance/404.json, templates/maintenance/500.json, templates/maintenance/502.json, templates/maintenance/503.json, templates/sites-enabled/perun-api-cert.conf.j2, templates/sites-enabled/perun-api.conf.j2
Defines JSON error messages for Perun RPC API.
=> JSON ErrorDocuments for APIs

files/perun_sync.py
* added empty members block to synchronized resources without members
=> fix: fix no members synchronization

defaults/main.yml, templates/sites-enabled/perun.conf.j2
- By default we have have no suffix.
=> Support custom suffix in old admin GUI

defaults/main.yml, templates/perun.properties.j2
- perun.auditlogReadLimit
- perun.archiveSpool
=> Added new options to perun.properties

templates/instance_configs/pwdresetInstanceConfig.json.j2
- Required for generic error report dialog.
=> Add new "config" property to pwdresetInstanceConfig.json.j2

defaults/main.yml, tasks/main.yml
- Added new property "perun_remote_logging_protocol" defaulting to "network".
=> Support new remote logging configuration

defaults/main.yml
- Might be breaking change, check vars for your perun instance before running this role.
=> Bump default postgres version to 17

defaults/main.yml, templates/instance_configs/instanceConfig.json.j2, templates/instance_configs/profileInstanceConfig.json.j2, templates/instance_configs/publicationsInstanceConfig.json.j2
- New property for NGUI 18.0.0+
- Default value is 1000
=> Allow per-instance configuration of export_limit NGUI property

templates/sites-enabled/perun-cert.conf.j2
- Fixed redirects in sites template.
=> Fix showing maintenance/static pages on cert-only domains

defaults/main.yml, tasks/main.yml, tasks/perun_auditlogger.yml, tasks/postgres_local.yml, tasks/postgres_perun.yml, tasks/postgres_remote.yml, templates/jdbc.properties.j2
changes needed to utilize remote PostgreSQL server in AWS
=> changes for remote PostgreSQL in AWS

tasks/postgres_local.yml, tasks/postgres_perun.yml, tasks/postgres_remote.yml
- Use base name "login_db" instead.
=> 'db' and 'database' aliases are deprecated in latest postgres modules
